# Generated by Django 4.2.1 on 2023-12-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='apreved_info',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_sent',
        ),
    ]
