# Generated by Django 5.0 on 2024-02-25 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_products_apreved_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
