# Generated by Django 4.2.1 on 2023-12-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicLevel',
        ),
        migrations.RemoveField(
            model_name='administrativepost',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='aldeia',
            name='village',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.DeleteModel(
            name='Religion',
        ),
        migrations.RemoveField(
            model_name='village',
            name='administrativepost',
        ),
        migrations.DeleteModel(
            name='AdministrativePost',
        ),
        migrations.DeleteModel(
            name='Aldeia',
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.DeleteModel(
            name='Village',
        ),
    ]
